In [7]:
import pandas as pd

In [8]:
# Load the dataset
pos = pd.read_csv("Data/palmmart_pos_sales.csv")
products= pd.read_excel("Data/palmmart_products.xlsx")
ecom = pd.read_json("Data/palmmart_ecommerce.json")

In [16]:
type(ecom)

pandas.core.frame.DataFrame

In [17]:
ecom

,order_id,customer_id,product_id,quantity,total_naira,order_date,status,branch
0,ORD-1001,637,2,3,962.54,2026-08-06,delivered,Lekki
1,ORD-1002,650,14,4,823.87,2026-08-04,delivered,Surulere
2,ORD-1003,574,8,2,1378.19,2026-08-06,delivered,Ikeja
3,ORD-1004,497,18,4,2864.54,2026-08-05,delivered,Victoria Island
4,ORD-1005,967,9,2,1172.66,2026-08-01,cancelled,Lekki
...,...,...,...,...,...,...,...,...
95,ORD-1096,798,5,5,1170.48,2026-08-07,delivered,Ikeja
96,ORD-1097,227,2,1,303.81,2026-08-07,delivered,Victoria Island
97,ORD-1098,805,15,4,2600.35,2026-08-04,delivered,Victoria Island
98,ORD-1099,469,10,2,986.90,2026-08-03,delivered,Lekki
99,ORD-1100,505,3,3,1087.59,2026-08-06,delivered,Lekki

In [19]:
# its important to check the shape of the dataframes to understand the number of rows and columns in each dataset. This will help us identify any potential issues  such as missing values or duplicates, and also give us an idea of the size of the data we are working with.
pos.shape
print(f"Shape of pos: {pos.shape}")
print("dtype of pos:", pos.dtypes)
print(f"shape of products: {products.shape}")
print(f"shape of ecom: {ecom.shape}")

Shape of pos: (415, 7)
dtype of pos: Transaction ID      int64
Branch             object
Product ID          int64
Qty                 int64
Unit Price        float64
Sale Date          object
Payment            object
dtype: object
shape of products: (20, 5)
shape of ecom: (100, 8)

In [21]:
pos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 415 entries, 0 to 414
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  415 non-null    int64
 1   Branch          415 non-null    object
 2   Product ID      415 non-null    int64
 3   Qty             415 non-null    int64
 4   Unit Price      379 non-null    float64
 5   Sale Date       415 non-null    object
 6   Payment         415 non-null    object
dtypes: float64(1), int64(3), object(3)
memory usage: 22.8+ KB

In [22]:
pos.describe()

       Transaction ID  Product ID         Qty   Unit Price
count      415.000000  415.000000  415.000000   379.000000
mean       195.318072   10.544578    4.672289   666.349657
std        116.712952    5.866248    2.233599   415.727599
min          1.000000    1.000000    1.000000   150.710000
25%         90.500000    5.000000    3.000000   326.490000
50%        193.000000   10.000000    5.000000   633.160000
75%        296.500000   16.000000    7.000000   859.040000
max        400.000000   20.000000    8.000000  2238.180000

In [30]:
# using all the checks on one dataframe 
"shape of pos: {pos.shape}"
"info of pos: {pos.info}"
"describe of pos: {pos.describe}"
"dtype of pos: pos.dtypes"
"head of pos: pos.head(5)"

'head of pos: pos.head(5)'

In [9]:
print(f"Shape of pos: {pos.shape}")

Shape of pos: (415, 7)